version: '3'
services:
  web:
    image: galic/todo_app
#    build: /home/bobi/Bobi/Finki/Semestar6/KIII - Kontinuirana Integracija i isporaka/KIII2025/todo_app
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo_app
  redis:
    image: redis